channels:
  - conda-forge
  - nodefaults

dependencies:
  # Required to work with JupyterHub
  - jupyterhub-singleuser>=3.0
  # Required to work with RStudio
  - jupyter-rsession-proxy>=2
  # Let's provide Jupyter Interfaces too
  - jupyterlab>=3.0
  - retrolab
  # Provide info on memory usage in JupyterLab & RetroLab
  - jupyter-resource-usage
  # People still wanna pull stuff, even if into RStudio
  - nbgitpuller==1.1.1
